language: node_js
node_js:
  - "0.10"
env:
  global:
    - NODE_ENV="test"
  matrix:
    - TEST_CMD="lint"
    - TEST_CMD="mocha"
cache:
  directories:
    - node_modules
script:
  - ./node_modules/.bin/grunt travis
after_script:
  - if [ "$TEST_CMD" = 'mocha' ]; then npm run coveralls; fi
